spring.application.name=backend

#Database Configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/direct_root?createDatabaseIfNotExist=true
spring.datasource.username=adithya
spring.datasource.password=2006
spring.datasource.hikari.maximum-pool-size=10

#JPA Configurations
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

#Token Data
jwt.expiration=864000000
jwt.secret=mySecretkey1234dew4mySecretkey1234dew4mySecretkey1234dew4mySecretkey1234dew4mySecretkey1234dew4